version: '3.8'

services:
  ldap-server:
    build: .
    image: openldap-test
    container_name: ldap-server
    ports:
      - "389:389"
    volumes:
      - ./data/ldap-data:/var/lib/ldap
      - ./data/ldap-config:/etc/ldap/slapd.d
    restart: unless-stopped
